#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \

# Void
alias \
	i="doas xbps-install -S" \
	u="i;doas xbps-install -u xbps;doas xbps-install -u" \
	r="doas xbps-remove -R" \
	rc="doas xbps-remove -Oo" \
	q="doas xbps-query -Rs" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \

# These common commands are just too long! Abbreviate them.
